//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoluntinderDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pairing
    {
        public string UserId { get; set; }
        public string PairedUser { get; set; }
        public bool Paired { get; set; }
        public long Id { get; set; }
        public Nullable<System.DateTime> MatchedOn { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
    }
}
